movie_project/movie_app/urls.py
from django.urls import path
from . import views

app_name = 'movie_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:c_slug>/', views.index, name='movies_by_genre'),
    path('login/details/', views.login, name='login'),
    path('register/details/', views.register, name='registration'),
    path('detail/<int:movie_id>/', views.detail, name='detail'),
    path('add/movie/', views.add, name='add'),
    path('logout', views.logout, name='logout'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('<int:id>/', views.edit, name='edit'),
    path('remove/<int:id>/', views.remove, name='remove'),
    path('edit_review/<int:id>/', views.edit_review, name='edit_review'),
    path('profile/view/', views.profilePage, name='profile'),
    path('editprofile/details/', views.edit_profile, name='editprofile'),
    path('filter/genre/<int:id>', views.genfilter, name='filter'),

]

movie_project/movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls')),
    path('search/', include('search_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/search_app/urls.py
from django.urls import path
from . import views


app_name = 'search_app'

urlpatterns = [
    path('search/', views.Search, name='Search'),
]

movie_project/templates/add.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    MVS
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <br><br>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12" style="text-align: center;">
            <br>
            <label style="color:white;"><h2>Enter Details Of Movie</h2></label><br><br>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
        </div>
        <div class="col-lg-8" style="color:white;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4">
                            <label style="transform: translateY(12%);letter-spacing:.1em;">Movie Name:</label><br><br>
                            <label style="transform: translateY(37%);letter-spacing:.1em;">Description:</label><br><br>
                            <label style="transform: translateY(62%);letter-spacing:.1em;">Release Year:</label><br><br>
                            <label style="transform: translateY(87%);letter-spacing:.1em;">Actors:</label><br><br>
                            <label style="transform: translateY(160%);letter-spacing:.1em;">Genre:</label><br><br>
                            <label style="transform: translateY(680%);letter-spacing:.1em;">Poster:</label><br><br>
                            <label style="transform: translateY(705%);letter-spacing:.1em;">YouTube link:</label><br><br>
                        </div>
                        <div class="col-lg-8">
                            <input type="text" name="name" placeholder="Enter Movie Name..." style="width: 400px;"><br><br>
                            <input type="text" name="desc" placeholder="Enter Description..." style="width: 400px;"><br><br>
                            <input type="number" name="year" placeholder="Enter Release Year..." style="width: 400px;"><br><br>
                            <input type="text" name="actors" placeholder="Mention Relevant Actors..." style="width: 400px;"><br><br>
                            <div class="col-md-3">
                                <div class="card text-left" style="width: 20rem;height: 10rem;overflow:scroll;">
                                    <div class="card-body">
                                    {% for i in gennames %}
                                        <input type="checkbox" name=genre value="{{i.name}}"> {{i.name}}<br>
                                    {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <br>
                            <input type="file" name="img" placeholder="Upload Movie Poster..." style="color:white;width: 400px;color:black;"><br><br>
                            <input type="url" name="youtube_url" placeholder="Enter Youtube Trailer URL..." style="width: 400px;"><br><br><br>
                            <input type="submit" value="Add Movie..." style="color:black;position:center;transform: translateX(-150%);">
                        </div>
                    </div>
                </div>
            </form>
            <br>
            {% for msg in messages %}
                <h5 style="margin-left: 10%;color:red;">{{msg}}</h5>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

movie_project/templates/delete.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}
    MVS
{% endblock %}
{% block title %}

{% endblock %}


{% block content %}
<form method="post">
<br><br><br>
    {% csrf_token %}
    <h2 style="color:white;text-align:center">Are you sure you want to delete this movie?</h2>
    <input type="submit" value="Yes" style="margin-left: 50%;">


</form>



{% endblock %}

movie_project/templates/detail.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Detail
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <img src="{{movie.img.url}}" width="100%">
        </div>
        <div class="col-lg-9" style="background-color:grey;">
            <h1 style="color:white;"><u>{{movie.name}}</u></h1>
            <h5 style="color:white;">{{movie.year}}</h5>
            <h5 style="color:white;">{{movie.genre}}</h5><br>
            <h5 style="color:white;">{{movie.desc}}</h5>
            <a href="{{movie.youtube_url}}" target="_blank" style="color:blue;">Watch trailer here...</a>
            <br><br>
            <h6 style="color:white;text-align:right;">--posted by {{movie.user_name}}</h6>
            {% if user.is_authenticated %}
                {% if request.user.username == movie.user_name %}
                    <a style="background-color:white" class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Edit</a>
                    <a style="background-color:red" class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            {% if user.is_authenticated %}
            <h4 style="text-align:center;">Leave a Review</h4>
            <form class="p-3 shadow" method="post" action="{% url 'movie_app:detail' movie.id %}">
                {% csrf_token %}
                <input type="hidden" name="movie_id" id="movie_id" value="{{movie.id}}">
                <div class="form-group">
                    <input type="text" name="review" placeholder="Leave a review.." style="width: 100%;" >
                </div>
                <div class="form-group">
                    Your Rating:<br>
                    <input type="radio" id="star-1" name="rating" value="1" /><label for="star-1"></label>
                    <input type="radio" id="star-2" name="rating" value="2" /><label for="star-2"></label>
                    <input type="radio" id="star-3" name="rating" value="3" /><label for="star-3"></label>
                    <input type="radio" id="star-4" name="rating" value="4" /><label for="star-4"></label>
                    <input type="radio" id="star-5" name="rating" value="5" /><label for="star-5"></label>
                </div>
                <input type="submit" class="btn btn-success" value="Submit">
            </form>
            {% for msg in messages %}
                <h6 style="margin-left: 10%;color:red;">{{msg}}</h6>
            {% endfor %}
            <br>
            {% endif %}
            <h4>Movie Reviews</h4>
            <br>
            <div class="card text-left" style="width: 100%;height: 30rem;overflow:scroll;">
            {% for review in review %}
                <div class="shadow card">
                    <div class="card-body" style="background-color:black;color:white;">
                        <h4 class="card-title" style="color:white;">{{review.user}}</h4>
                        <h5>Rating: {{review.rating}}</h5>
                        <h6>"{{review.review}}"</h6>
                        <h6>{{review.created_at}}</h6>
                        {% if user.is_authenticated %}
                            {% if request.user == review.user %}
                                <a style="color:white;position: absolute;right: 25px;top:15px;" href="{% url 'movie_app:edit_review' review.id %}">Edit</a>
                                <a style="color:white;position: absolute;right: 50px;top:15px;" href="{% url 'movie_app:remove' review.id %}">Remove</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            <br>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

movie_project/templates/edit.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Edit
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12" style="text-align: center;">
            <br>
            <label style="color:white;"><h1>Update Details</h1></label><br><br>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-8">
            <form method="POST" enctype="multipart/form-data" style="color:white;">
              {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4">
                            <label style="transform: translateY(12%);letter-spacing:.1em;">Movie Name:</label><br><br>
                            <label style="transform: translateY(37%);letter-spacing:.1em;">Description:</label><br><br>
                            <label style="transform: translateY(62%);letter-spacing:.1em;">Release Year:</label><br><br>
                            <label style="transform: translateY(87%);letter-spacing:.1em;">Actors:</label><br><br>
                            <label style="transform: translateY(160%);letter-spacing:.1em;">Genre:</label><br><br>
                            <label style="transform: translateY(680%);letter-spacing:.1em;">Poster:</label><br><br>
                            <label style="transform: translateY(705%);letter-spacing:.1em;">YouTube link:</label><br><br>
                        </div>
                        <div class="col-lg-8">
                            <input type="text" name="name" placeholder="{{movie.name}}" style="width: 400px;"><br><br>
                            <input type="text" name="desc" placeholder="{{movie.desc}}" style="width: 400px;"><br><br>
                            <input type="number" name="year" placeholder="{{movie.year}}" style="width: 400px;"><br><br>
                            <input type="text" name="actors" placeholder="{{movie.actors}}" style="width: 400px;"><br><br>
                            <div class="col-md-3">
                                <div class="card text-left" style="width: 20rem;height: 10rem;overflow:scroll;">
                                    <div class="card-body">
                                    {% for i in gennames %}
                                        <input type="checkbox" name=genre value="{{i.name}}"> {{i.name}}<br>
                                    {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <br>
                            <input type="file" name="img" placeholder="Upload Movie Poster..." style="color:white;width: 400px;color:black;"><br><br>
                            <input type="url" name="youtube_url" placeholder="{{movie.url}}" style="width: 400px;"><br><br><br>
                            <input type="submit" value="Update" style="color:black;position:center;transform: translateX(-150%);">
                        </div>
                    </div>
                </div>
            </form>
            {% for msg in messages %}
            <h5 style="margin-left: 10%;color:red;">{{msg}}</h5>
            {% endfor %}
        </div>
    </div>
</div>




{% endblock %}

movie_project/templates/edit_profile.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Edit Profile
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12" style="text-align: center;">
            <br>
            <label style="color:white;"><h1>Edit your profile:</h1></label><br><br>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-8">
            <form method="POST" enctype="multipart/form-data" style="color:white;">
              {% csrf_token %}
              <div class="container">
                    <div class="row">
                        <div class="col-lg-4">
                            <label style="transform: translateY(12%);letter-spacing:.1em;">Username:</label><br><br>
                            <label style="transform: translateY(37%);letter-spacing:.1em;">First Name:</label><br><br>
                            <label style="transform: translateY(62%);letter-spacing:.1em;">Last Name:</label><br><br>
                            <label style="transform: translateY(87%);letter-spacing:.1em;">E-mail:</label><br><br>
                        </div>
                        <div class="col-lg-8">
                            <input type="text" name="Username" placeholder="Will use '{{user.username}}' if left blank..." style="width: 400px;"><br><br>
                            <input type="text" name="first_name" placeholder="Enter First Name..." style="width: 400px;"><br><br>
                            <input type="text" name="last_name" placeholder="Enter Last Name..." style="width: 400px;"><br><br>
                            <input type="text" name="mail" placeholder="Will use '{{user.email}}' if left blank..." style="width: 400px;"><br><br>
                            <input type="submit" value="Update Profile" style="color:black;position:center;transform: translateX(-150%);">
                        </div>
                    </div>
                </div>
            </form>
            {% for msg in messages %}
            <h5 style="margin-left: 10%;color:red;">{{msg}}</h5>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

movie_project/templates/edit_review.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Edit Review
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12" style="text-align: center;">
            <br>
            <label style="color:white;"><h1>Edit your review:</h1></label><br><br>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <form method="POST" enctype="multipart/form-data" style="color:white;">
              {% csrf_token %}
              <input type="hidden" name="movie_id" id="movie_id" value="{{movie.id}}">
                <div class="form-group">
                    <input type="text" name="review" placeholder="{{review.review}}" style="width: 100%;" >
                </div>
                <div class="form-group">
                    Your Rating:<br>
                    <input type="radio" id="star-1" name="rating" value="1" /><label for="star-1"></label>
                    <input type="radio" id="star-2" name="rating" value="2" /><label for="star-2"></label>
                    <input type="radio" id="star-3" name="rating" value="3" /><label for="star-3"></label>
                    <input type="radio" id="star-4" name="rating" value="4" /><label for="star-4"></label>
                    <input type="radio" id="star-5" name="rating" value="5" /><label for="star-5"></label>
                </div>
                <input type="submit" class="btn btn-success" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

movie_project/templates/filter.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Filter
{% endblock %}


{% block content %}
<h1 style="text-align:center;">{{genre.name}}</h1>
<div class="container">
    <div class="row">
        {% for i in movies %}
            {% if genre.name in i.genre %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-3" style="padding-top:10px;padding-left:10px;padding-bottom:10px;padding-right:10px;">
                    <div class="card text-center" style="width:13rem;">
                        <a href="{% url 'movie_app:detail' i.id %}"><img class="card_img_top" src="{{i.img.url}}" alt="{{i.name}}" style="width:200px;"></a>
                        <div class="card-body">
                            <h6 class="card-title">{{i.name}}</h6>
                            <p class="card-text">({{i.year}})</p>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

movie_project/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/6b31a6c5f2.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="font-family: 'Oswald', serif;background-color:#34495E;color:white;background-image:url({% static 'img/bg.png' %});background-size: cover;">
    <div class="my_header">
        {% include 'navbar.html' %}
        <div>
            <img class="my_image my_image_padding" style="height:75%;" src="{% static 'img/banner.png' %}" alt="Our Banner">
        </div>
        <br><br>
        <div class="main_content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

movie_project/templates/index.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Home
{% endblock %}


{% block content %}
<div class="container" style="overflow:scroll;height:1300px;padding-bottom:30px;">
    <div class="row">
        {% for gen in gennames %}
            <h1>{{gen.name}}</h1>
            {% for i in movie_list %}
                {% if gen.name in i.genre %}
                    <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-3" style="padding-top:10px;padding-left:10px;padding-bottom:10px;padding-right:10px;">
                        <div class="card text-center" style="width:13rem;">
                            <a href="{% url 'movie_app:detail' i.id %}"><img class="card_img_top" src="{{i.img.url}}" alt="{{i.name}}" style="width:200px;"></a>
                            <div class="card-body">
                                <h6 class="card-title">{{i.name}}</h6>
                                <p class="card-text">({{i.year}})</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </div>
</div>

{% endblock %}

movie_project/templates/login.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Login
{% endblock %}


{% block content %}
<div class="container" style="transform: translateY(50%);">
    <div class="row">
        <div class="col-lg-12">
            {% for msg1 in message %}
            <h3 style="text-align:center;color:white;">{{msg1}}</h3>
            {% endfor %}
            <br>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12" style="text-align: center;">
            <br>
            <label><h2>Login</h2></label><br><br>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
        </div>
        <div class="col-lg-8" style="color:white;">
            <form action="{% url 'movie_app:login' %}" method="post">
                {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4">
                            <label style="transform: translate(120%,12%);letter-spacing:.1em;">Username:</label><br><br>
                            <label style="transform: translate(131%,37%);letter-spacing:.1em;">Password:</label><br><br>
                        </div>
                        <div class="col-lg-8">
                            <input type="text" name="Username" placeholder="Enter your Username" style="width: 300px;transform: translateX(-20%);"><br><br>
                            <input type="password" name="pwd" placeholder="Enter your Password" style="width: 300px;transform: translateX(-20%)"><br><br>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <input type="submit" value="Login" style="margin-left: 21%">
                        </div>
                    </div>
                </div>
            </form>
            <br>
            {% for msg in messages %}
                <h5 style="margin-left: 10%;color:red;">{{msg}}</h5>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

movie_project/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a href="/"><img class="logo_img" src="{% static 'img/logo.png' %}" alt="logo" style="width:90px;height:40px;"></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:white;">
            Genres
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for gen in gennames %}
            <li><a class="dropdown-item" href="{% url 'movie_app:filter' gen.id %}" style="color:black;">{{gen.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li>
        <form class="d-flex" action="{% url 'search_app:Search' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search.." name="q" aria-label="Search" style="width: 500px;">
        <button class="btn btn-outline-success" type="submit" style="background-color:#5DADE2;color:white"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
        </li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'movie_app:add' %}" style="color:white;position: absolute;left: 800px;top:15px;">+ Add Movie</a>
        </li>
        <li>
            <a href="{% url 'movie_app:profile' %}" style="color:grey;position: absolute;right: 80px;top:15px;">Hello, {{user.username}}</a>
            <a href="{% url 'movie_app:logout' %}" style="color:white;position: absolute;right: 25px;top:15px;">Logout</a>
          {% else %}
            <a style="color:white;position: absolute;right: 90px;top:15px;" href="{% url 'movie_app:registration' %}">Register</a>
            <a style="color:white;position: absolute;right: 25px;top:15px;" href="{% url 'movie_app:login' %}">Sign In</a>

        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

movie_project/templates/profile.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Profile
{% endblock %}


{% block content %}
<br><br><br>
<h2 style="text-align:center;">Your Profile</h2>
<br>
{% if user.is_authenticated %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <table style="width:80%;position:center;margin-left: 25%" >
                    <tr>
                        <th><u>Username:</u></th>
                        <td>{{user.username}}</td>
                    </tr>
                    <tr>
                        <th><u>First Name:</u></th>
                        <td>{{user.first_name}}</td>
                    </tr>
                    <tr>
                        <th><u>Last Name:</u></th>
                        <td>{{user.last_name}}</td>
                    </tr>
                    <tr>
                        <th><u>E-mail:</u></th>
                        <td>{{user.email}}</td>
                    </tr>
                </table>
                <a href="{% url 'movie_app:editprofile' %}" style="position:center;margin-left: 47%">Edit profile...</a>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}

movie_project/templates/remove.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Remove
{% endblock %}


{% block content %}
<form method="post" style="position:center;">

    {% csrf_token %}
    <p style="color:white;">Are you sure you want to remove your review?</p>
    <input type="submit" value="Yes">


</form>



{% endblock %}

movie_project/templates/search.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
    <div>
        <p class="text-center my_search_text">Showing results for: <b>"{{query}}"</b></p>
    </div>
    <div>
        <div class="container">
            <div class="row">
                {% for i in movies %}
                    {% if query|title in i.name or query|lower in i.name or query in i.name %}
                        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-3">
                            <div class="card text-center" style="width:13rem;">
                                <a href="{% url 'movie_app:detail' i.id %}"><img class="card_img_top" src="{{i.img.url}}" alt="{{i.name}}" style="width:200px;"></a>
                                <div class="card-body">
                                    <h6 class="card-title">{{i.name}}</h6>
                                    <p class="card-text">({{i.year}})</p>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <div class="row_mx_auto">
                        <p class="text-center my_search_text"> No results.</p>
                    </div>
                {% endfor %}
            </div>
            <br>
        </div>
    </div>
{% endblock %}